---
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - jaeger
